### PR TITLE
Dave add new node attributes

### LINKED ISSUE #49: Filter Area doesn't work with new Backend
### Environment

 * Release number or git hash: 
 * Browser: 
 * Deployed / Local: 
---

### Steps to reproduce the bug

1. Open a list of ... / Search ...
2. Do something else

### Observed Behavior

> Please provide a short description of the actual behavior you observed
> If applicable, add screenshots to help explain your problem.
> - Any unexpected output or action (or lack of expected output or action)
> - Web browser console errors (including tracebacks)
> - Server errors (relevant messages and tracebacks)
> - Static or animated images showing the UI behavior

### Expected Behavior

> Please provide a short description which behavior you expected from your steps

Thanks for taking the time to fill out this bug report 🤗
Make sure there aren't any open/closed issues for this topic 😃

### PR DESCRIPTION
**Pull request by DavidDeutz**
Added all kind of filtering like global filter, hide button and icon filtering.

### CODE REVIEW

File: src/GeneGraph.tsx [hunk 1]
```diff
@@ -34,6 +33,8 @@ export function GeneGraph(props: GeneGraphProps) {
     limit: 1000,
   });
 
+  console.log()
```
Comment (0Falli0) [inline src/GeneGraph.tsx:36]: please remove unnecessary logging

**Review by 0Falli0 — APPROVED** [review]
very well done, improved functionality greatly
